# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20170402_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='object_id',
            field=models.AutoField(max_length=50, primary_key=True, serialize=False, verbose_name='\u4e3b\u952e'),
        ),
    ]
